name: virtual_city
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # state mangment
  flutter_bloc: ^8.0.1

  # local storge
  shared_preferences: ^2.0.15

  # http
  dio: ^4.0.6

  # UI
  sizer: ^2.0.15
  circle_nav_bar: ^1.0.2
  carousel_slider: ^4.1.1
  flutter_profile_picture: ^2.0.0

  bloc:
  curved_navigation_bar: ^1.0.3
  fancy_shimmer_image: ^2.0.0+2
  auto_size_text: ^3.0.0

  flutter_svg: ^1.0.3

  youtube_player_flutter: ^8.1.0
  google_fonts: ^2.3.2
  flutter_carousel_slider: ^1.0.8
  awesome_dialog: ^2.2.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
